# üìä An√°lisis B√°sico de Datos en Python

## üéØ Objetivo de la Clase
- Aprender a manipular y analizar datos tabulares en Python utilizando **pandas**.
- Explorar datos con funciones clave para obtener informaci√≥n √∫til.

In [ ]:
import pandas as pd
import numpy as np

## 1Ô∏è‚É£ Carga de Datos en Pandas

In [ ]:
# Crear un DataFrame de ejemplo con m√°s datos
data = {'Nombre': ['Ana', 'Carlos','Ana', 'David', 'Elena', 'Fernando', 'Gabriela', 'Hugo', 'Isabel', 'Juan', 'Karen'],
        'Edad': [25, 30,25, 35, 40, 45, 50, 55, 29, 33, 41],
        'Salario': [2000, 3500,2000, 4000, 2500, 5000, 6000, 7000, 3000, 4100, 5400],
        'Departamento': ['Ventas', 'TI','Ventas', 'TI', 'Marketing', 'Ventas', 'RRHH', 'Ventas', 'TI', 'Marketing', 'RRHH'],
        'A√±os_Experiencia': [1, 5,1, 7, 2, 10, 15, 20, 3, 8, 12]}

df = pd.DataFrame(data)
df

      Nombre  Edad  Salario Departamento  A√±os_Experiencia
0        Ana    25     2000       Ventas                 1
1     Carlos    30     3500           TI                 5
2        Ana    25     2000       Ventas                 1
3      David    35     4000           TI                 7
4      Elena    40     2500    Marketing                 2
5   Fernando    45     5000       Ventas                10
6   Gabriela    50     6000         RRHH                15
7       Hugo    55     7000       Ventas                20
8     Isabel    29     3000           TI                 3
9       Juan    33     4100    Marketing                 8
10     Karen    41     5400         RRHH                12

In [ ]:
type(df)

pandas.core.frame.DataFrame

## 2Ô∏è‚É£ Inspecci√≥n General de los Datos

In [ ]:
df.shape

(11, 5)

In [ ]:
# Mostrar las primeras filas
df.head(2)

   Nombre  Edad  Salario Departamento  A√±os_Experiencia
0     Ana    25     2000       Ventas                 1
1  Carlos    30     3500           TI                 5

In [ ]:
# Mostrar las primeras filas y √∫ltimas filas
df.tail(3)

    Nombre  Edad  Salario Departamento  A√±os_Experiencia
8   Isabel    29     3000           TI                 3
9     Juan    33     4100    Marketing                 8
10   Karen    41     5400         RRHH                12

In [ ]:
# Informaci√≥n sobre el DataFrame
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11 entries, 0 to 10
Data columns (total 5 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Nombre            11 non-null     object
 1   Edad              11 non-null     int64
 2   Salario           11 non-null     int64
 3   Departamento      11 non-null     object
 4   A√±os_Experiencia  11 non-null     int64
dtypes: int64(3), object(2)
memory usage: 572.0+ bytes

In [ ]:
# Resumen estad√≠stico detallado
df.describe()

            Edad      Salario  A√±os_Experiencia
count  11.000000    11.000000         11.000000
mean   37.090909  4045.454545          7.636364
std    10.014535  1656.721845          6.168837
min    25.000000  2000.000000          1.000000
25%    29.500000  2750.000000          2.500000
50%    35.000000  4000.000000          7.000000
75%    43.000000  5200.000000         11.000000
max    55.000000  7000.000000         20.000000

## 3Ô∏è‚É£ Selecci√≥n de Columnas

In [ ]:
df["Nombre"]

0          Ana
1       Carlos
2          Ana
3        David
4        Elena
5     Fernando
6     Gabriela
7         Hugo
8       Isabel
9         Juan
10       Karen
Name: Nombre, dtype: object

In [ ]:
# Seleccionar una sola columna
col_name = df['Nombre']

In [ ]:
col_name

0          Ana
1       Carlos
2          Ana
3        David
4        Elena
5     Fernando
6     Gabriela
7         Hugo
8       Isabel
9         Juan
10       Karen
Name: Nombre, dtype: object

In [ ]:
# Seleccionar m√∫ltiples columnas
df[['Nombre', 'Salario', "Edad"]]

      Nombre  Salario  Edad
0        Ana     2000    25
1     Carlos     3500    30
2        Ana     2000    25
3      David     4000    35
4      Elena     2500    40
5   Fernando     5000    45
6   Gabriela     6000    50
7       Hugo     7000    55
8     Isabel     3000    29
9       Juan     4100    33
10     Karen     5400    41

In [ ]:
# Seleccionar usando loc
df.loc[:3, ['Edad', 'Salario']]

   Edad  Salario
0    25     2000
1    30     3500
2    25     2000
3    35     4000

In [ ]:
# Seleccionar usando iloc (posici√≥n de columna)
df.iloc[:5, 1:3
        ]

   Edad  Salario
0    25     2000
1    30     3500
2    25     2000
3    35     4000
4    40     2500

## 4Ô∏è‚É£ Filtrado de Datos

In [ ]:
# Filtrar empleados con salario mayor a 4000
df[df['Salario'] > 4000]

      Nombre  Edad  Salario Departamento  A√±os_Experiencia
5   Fernando    45     5000       Ventas                10
6   Gabriela    50     6000         RRHH                15
7       Hugo    55     7000       Ventas                20
9       Juan    33     4100    Marketing                 8
10     Karen    41     5400         RRHH                12

In [ ]:
# Filtrar empleados de TI con m√°s de 5 a√±os de experiencia
df[(df['Departamento'] == 'TI') | (df['A√±os_Experiencia'] > 5)]

      Nombre  Edad  Salario Departamento  A√±os_Experiencia
1     Carlos    30     3500           TI                 5
3      David    35     4000           TI                 7
5   Fernando    45     5000       Ventas                10
6   Gabriela    50     6000         RRHH                15
7       Hugo    55     7000       Ventas                20
8     Isabel    29     3000           TI                 3
9       Juan    33     4100    Marketing                 8
10     Karen    41     5400         RRHH                12

In [ ]:
# Filtrar empleados de Marketing o RRHH
df[df['Departamento'].isin(['Marketing', 'RRHH'])]

     Nombre  Edad  Salario Departamento  A√±os_Experiencia
3     Elena    40     2500    Marketing                 2
5  Gabriela    50     6000         RRHH                15
8      Juan    33     4100    Marketing                 8
9     Karen    41     5400         RRHH                12

## 5Ô∏è‚É£ Agrupaci√≥n y Estad√≠sticas B√°sicas

###5.0 Agrupaciones 1 Variable

In [ ]:
# Indicadores por variable
df['Salario'].mean()

4045.4545454545455

In [ ]:
# Indicadores por variable
df['Salario'].max()

7000

In [ ]:
# Indicadores por variable
df['Salario'].min()

2000

In [ ]:
# Indicadores por variable
df['Salario'].sum()

44500

In [ ]:
df["Salario"].quantile(0.5)

4000.0

###5.1 Frecuencia, Agrupaciones de variables categoricas

In [ ]:
df['Departamento'].value_counts()

Departamento
Ventas       4
TI           3
Marketing    2
RRHH         2
Name: count, dtype: int64

### 5.2 Group By

In [ ]:
# Agrupar por departamento y calcular la media salarial
df[df['Salario']==df['Salario'].max()]["Nombre"]

7    Hugo
Name: Nombre, dtype: object

In [ ]:
df['Salario'].max()

7000

In [ ]:
df_filtrado = df[["Nombre", "Edad","Salario"]]

In [ ]:
df_mayores = df_filtrado[df_filtrado["Edad"]>25]

In [ ]:
df_mayores

      Nombre  Edad  Salario
1     Carlos    30     3500
3      David    35     4000
4      Elena    40     2500
5   Fernando    45     5000
6   Gabriela    50     6000
7       Hugo    55     7000
8     Isabel    29     3000
9       Juan    33     4100
10     Karen    41     5400

In [ ]:
tabla =

In [ ]:
tabla["Nombre"]

7    Hugo
Name: Nombre, dtype: object

In [ ]:
# Agrupar por departamento y contar empleados
df.groupby('Departamento')['Nombre'].count()

Departamento
Marketing    2
RRHH         2
TI           3
Ventas       4
Name: Nombre, dtype: int64

## 6Ô∏è‚É£ Ordenamiento de Datos

In [ ]:
# Ordenar por salario de    mayor a menor
df.sort_values(by='Salario', ascending=False)

      Nombre  Edad  Salario Departamento  A√±os_Experiencia
7       Hugo    55     7000       Ventas                20
6   Gabriela    50     6000         RRHH                15
10     Karen    41     5400         RRHH                12
5   Fernando    45     5000       Ventas                10
9       Juan    33     4100    Marketing                 8
3      David    35     4000           TI                 7
1     Carlos    30     3500           TI                 5
8     Isabel    29     3000           TI                 3
4      Elena    40     2500    Marketing                 2
0        Ana    25     2000       Ventas                 1
2        Ana    25     2000       Ventas                 1

In [ ]:
# Ordenar por a√±os de experiencia y luego por salario
df.sort_values(by=['A√±os_Experiencia', 'Salario'], ascending=[False, True])

     Nombre  Edad  Salario Departamento  A√±os_Experiencia
6      Hugo    55     7000       Ventas                20
5  Gabriela    50     6000         RRHH                15
9     Karen    41     5400         RRHH                12
4  Fernando    45     5000       Ventas                10
8      Juan    33     4100    Marketing                 8
2     David    35     4000           TI                 7
1    Carlos    30     3500           TI                 5
7    Isabel    29     3000           TI                 3
3     Elena    40     2500    Marketing                 2
0       Ana    25     2000       Ventas                 1

## 7Ô∏è‚É£ Creaci√≥n de Nuevas Columnas

In [ ]:
df.head()

   Nombre  Edad  Salario Departamento  A√±os_Experiencia
0     Ana    25     2000       Ventas                 1
1  Carlos    30     3500           TI                 5
2     Ana    25     2000       Ventas                 1
3   David    35     4000           TI                 7
4   Elena    40     2500    Marketing                 2

In [ ]:
# Crear una nueva columna con el salario anual
df['Salario_Anual'] = df['Salario'] * 12

In [ ]:
df.head()

   Nombre  Edad  Salario Departamento  A√±os_Experiencia  Salario_Anual
0     Ana    25     2000       Ventas                 1          24000
1  Carlos    30     3500           TI                 5          42000
2     Ana    25     2000       Ventas                 1          24000
3   David    35     4000           TI                 7          48000
4   Elena    40     2500    Marketing                 2          30000

In [ ]:

# Crear una nueva columna indicando si tiene m√°s de 5 a√±os de experiencia
df["Numero"] = 2
df.loc[:3,"Numero"] = 5
df

,Nombre,Edad,Salario,Departamento,A√±os_Experiencia,Salario_Anual,Numero
0,Ana,25,2000,Ventas,1,24000,5
1,Carlos,30,3500,TI,5,42000,5
2,Ana,25,2000,Ventas,1,24000,5
3,David,35,4000,TI,7,48000,5
4,Elena,40,2500,Marketing,2,30000,2
5,Fernando,45,5000,Ventas,10,60000,2
6,Gabriela,50,6000,RRHH,15,72000,2
7,Hugo,55,7000,Ventas,20,84000,2
8,Isabel,29,3000,TI,3,36000,2
9,Juan,33,4100,Marketing,8,49200,2
10,Karen,41,5400,RRHH,12,64800,2

##DROP

In [ ]:
df.head()

,Nombre,Edad,Salario,Departamento,A√±os_Experiencia,Salario_Anual,Experiencia_Alta,Numero
0,Ana,25,2000,Ventas,1,24000,False,2
1,Carlos,30,3500,TI,5,42000,False,2
2,Ana,25,2000,Ventas,1,24000,False,2
3,David,35,4000,TI,7,48000,True,2
4,Elena,40,2500,Marketing,2,30000,False,12

In [ ]:
df_clean = df.drop(columns=['Numero'], axis=1)

In [ ]:
df_clean.head()

,Nombre,Edad,Salario,Departamento,A√±os_Experiencia,Salario_Anual,Experiencia_Alta
0,Ana,25,2000,Ventas,1,24000,False
1,Carlos,30,3500,TI,5,42000,False
2,Ana,25,2000,Ventas,1,24000,False
3,David,35,4000,TI,7,48000,True
4,Elena,40,2500,Marketing,2,30000,False

## 8Ô∏è‚É£ Eliminaci√≥n de Valores Duplicados

In [ ]:
# Verificar si hay duplicados
df.duplicated().sum()

1

In [ ]:

# Eliminar duplicados si existen
df.drop_duplicates(inplace=True)
df

,Nombre,Edad,Salario,Departamento,A√±os_Experiencia,Salario_Anual,Experiencia_Alta,Numero
0,Ana,25,2000,Ventas,1,24000,False,2.0
1,Carlos,30,3500,TI,5,42000,False,2.0
3,David,35,4000,TI,7,48000,True,2.0
4,Elena,40,2500,Marketing,2,30000,False,NaN
5,Fernando,45,5000,Ventas,10,60000,True,NaN
6,Gabriela,50,6000,RRHH,15,72000,True,NaN
7,Hugo,55,7000,Ventas,20,84000,True,NaN
8,Isabel,29,3000,TI,3,36000,False,NaN
9,Juan,33,4100,Marketing,8,49200,True,NaN
10,Karen,41,5400,RRHH,12,64800,True,NaN

## 9Ô∏è‚É£ Manejo de Valores Nulos

In [ ]:
# Introducir valores nulos para ejemplo
df.loc[2, 'Salario'] = np.nan
df.loc[5, 'Edad'] = np.nan

In [ ]:
df.head()

,Nombre,Edad,Salario,Departamento,A√±os_Experiencia,Salario_Anual,Experiencia_Alta,Numero
0,Ana,25.0,2000.0,Ventas,1.0,24000.0,False,2.0
1,Carlos,30.0,3500.0,TI,5.0,42000.0,False,2.0
3,David,35.0,4000.0,TI,7.0,48000.0,True,2.0
4,Elena,40.0,2500.0,Marketing,2.0,30000.0,False,NaN
5,Fernando,NaN,5000.0,Ventas,10.0,60000.0,True,NaN

In [ ]:
# Verificar valores nulos
df.isnull().sum()

Nombre              1
Edad                2
Salario             1
Departamento        1
A√±os_Experiencia    1
Salario_Anual       1
Experiencia_Alta    1
Numero              8
dtype: int64

In [ ]:
df.head()

,Nombre,Edad,Salario,Departamento,A√±os_Experiencia,Salario_Anual,Experiencia_Alta,Numero
0,Ana,25.0,2000.0,Ventas,1.0,24000.0,False,2.0
1,Carlos,30.0,3500.0,TI,5.0,42000.0,False,2.0
3,David,35.0,4000.0,TI,7.0,48000.0,True,2.0
4,Elena,40.0,2500.0,Marketing,2.0,30000.0,False,NaN
5,Fernando,NaN,5000.0,Ventas,10.0,60000.0,True,NaN

In [ ]:
# Rellenar valores nulos con la media de la columna
df['Edad'].fillna(df['Edad'].mean().round(0), inplace=True)
df

<ipython-input-54-15dbfd10add2>:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Edad'].fillna(df['Edad'].mean().round(0), inplace=True)

,Nombre,Edad,Salario,Departamento,A√±os_Experiencia,Salario_Anual,Experiencia_Alta,Numero
0,Ana,25.0,2000.0,Ventas,1.0,24000.0,False,2.0
1,Carlos,30.0,3500.0,TI,5.0,42000.0,False,2.0
3,David,35.0,4000.0,TI,7.0,48000.0,True,2.0
4,Elena,40.0,2500.0,Marketing,2.0,30000.0,False,NaN
5,Fernando,38.0,5000.0,Ventas,10.0,60000.0,True,NaN
6,Gabriela,50.0,6000.0,RRHH,15.0,72000.0,True,NaN
7,Hugo,55.0,7000.0,Ventas,20.0,84000.0,True,NaN
8,Isabel,29.0,3000.0,TI,3.0,36000.0,False,NaN
9,Juan,33.0,4100.0,Marketing,8.0,49200.0,True,NaN
10,Karen,41.0,5400.0,RRHH,12.0,64800.0,True,NaN
2,NaN,38.0,NaN,NaN,NaN,NaN,NaN,NaN

## üîü Aplicaci√≥n de Funciones Personalizadas

In [ ]:
# Crear una funci√≥n para clasificar empleados seg√∫n experiencia
def clasificar_experiencia(anios):
    if anios < 3:
        return 'Junior'
    elif anios < 10:
        return 'Mid-Level'
    else:
        return 'Senior'

df['Nivel_Experiencia'] = df['A√±os_Experiencia'].apply(clasificar_experiencia)
df

,Nombre,Edad,Salario,Departamento,A√±os_Experiencia,Salario_Anual,Experiencia_Alta,Numero,Nivel_Experiencia
0,Ana,25.0,2000.0,Ventas,1.0,24000.0,False,2.0,Junior
1,Carlos,30.0,3500.0,TI,5.0,42000.0,False,2.0,Mid-Level
3,David,35.0,4000.0,TI,7.0,48000.0,True,2.0,Mid-Level
4,Elena,40.0,2500.0,Marketing,2.0,30000.0,False,NaN,Junior
5,Fernando,38.0,5000.0,Ventas,10.0,60000.0,True,NaN,Senior
6,Gabriela,50.0,6000.0,RRHH,15.0,72000.0,True,NaN,Senior
7,Hugo,55.0,7000.0,Ventas,20.0,84000.0,True,NaN,Senior
8,Isabel,29.0,3000.0,TI,3.0,36000.0,False,NaN,Mid-Level
9,Juan,33.0,4100.0,Marketing,8.0,49200.0,True,NaN,Mid-Level
10,Karen,41.0,5400.0,RRHH,12.0,64800.0,True,NaN,Senior
2,NaN,38.0,NaN,NaN,NaN,NaN,NaN,NaN,Senior

## üìå Conclusiones
- `describe()`, `info()`, y `head()` permiten inspeccionar los datos.
- `groupby()` y `value_counts()` generan estad√≠sticas √∫tiles.
- `apply()` nos permite crear funciones personalizadas para modificar los datos.
- `pivot_table()` y `crosstab()` ayudan a analizar mejor los datos.